#pragma once

#define HARDWARE_VERSION "2.3.2"
#define USE_INTERNAL_USB_CDC 0

#define CORE_HAS_SCREEN 0
#define CORE_HAS_ACCELEROMETER 0
#define CORE_HAS_ETHERNET 0
#define CORE_HAS_LOCAL_AUDIO_VISUAL 0
#define CORE_HAS_LOCAL_CHANNEL_OUTPUTS 0
#define CORE_NFC_READER_PN532 1
#define CORE_MAX_CHANNELS 1

#define PIN_NFC_POWER 8
#define PIN_NFC_CS 6
#define PIN_NFC_RST 4
#define PIN_NFC_IRQ 5
#define PIN_SPI_SCK 17
#define PIN_SPI_MISO 16
#define PIN_SPI_MOSI 7
#define PIN_INTERRUPT 37
#define PIN_ONE_WIRE 1

#define PIN_FRONTEND_TX 9
#define PIN_FRONTEND_RX 19