; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[platformio]
; This is what is built and uploaded by default when you run `pio run` or `pio run --target upload`.
;default_envs = core-v3-0-0

[env:core-v3-0-0]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = core-v3-0-0
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions/core_v3_8mb_spiffs.csv
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
build_flags =
    -D CORE_VARIANT_HEADER=\"variants/CoreV3_0_0.h\"
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D PIOENV_NAME=\"$PIOENV\"
lib_deps =
    paulstoffregen/OneWire
    bblanchon/ArduinoJson
    links2004/WebSockets
    marian-craciunescu/ESP32Ping
    hideakitai/MQTTPubSubClient
    adafruit/Adafruit NeoPixel
    sparkfun/SparkFun LIS2DH12 Arduino Library
    https://github.com/iwanders/MFRC630.git
    fbiego/ESP32Time

[env:core-v2-3-2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = core-v2-3-2
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions/core_v2_min_spiffs.csv
build_flags =
    -D CORE_VARIANT_HEADER=\"variants/CoreV2_3_2.h\"
    -D PIOENV_NAME=\"$PIOENV\"
build_src_filter =
    +<*>
    -<DisplayController.cpp>
lib_deps =
    paulstoffregen/OneWire
    bblanchon/ArduinoJson
    links2004/WebSockets
    marian-craciunescu/ESP32Ping
    hideakitai/MQTTPubSubClient
    adafruit/Adafruit PN532
    fbiego/ESP32Time